linters:
  enable:
    - asciicheck
    - bodyclose
    # - depguard
    - dogsled
    - dupl
    - errcheck
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    - goconst
    # - gocritic
    # - gocyclo
    # - godox
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    # - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - stylecheck
    # - typecheck
    - unconvert
    # - unparam
    - unused
    # - whitespace
    # - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-same-issues: 50

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  goconst:
    min-len: 5
    min-occurrences: 5
    ignore-tests: true
  misspell:
    locale: US
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        severity: warning
        disabled: false
        arguments:
          - allowRegex: "^_"
