version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused

  # disabled linters:
  # - depguard
  # - funlen
  # - gochecknoglobals
  # - gochecknoinits
  # - gocognit
  # - gocritic
  # - gocyclo
  # - godox
  # - interfacer
  # - lll
  # - typecheck
  # - unparam
  # - whitespace
  # - wsl
  settings:
    dogsled:
      max-blank-identifiers: 3
    goconst:
      min-len: 5
      min-occurrences: 5
    misspell:
      locale: US
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
