---
with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName | lower}}.go"
log-level: "warn"
disable-version-string: true
all: false
packages:
  github.com/dashpay/tenderdash/abci/client:
    interfaces:
      Client:
  github.com/dashpay/tenderdash/abci/types:
    interfaces:
      Application:
  github.com/dashpay/tenderdash/dash/core:
    interfaces:
      Client:
  github.com/dashpay/tenderdash/internal/consensus:
    interfaces:
      Gossiper:
  github.com/dashpay/tenderdash/internal/consensus/versioned/selectproposer:
    interfaces:
      ProposerSelector:
  github.com/dashpay/tenderdash/internal/evidence:
    interfaces:
      BlockStore:
  github.com/dashpay/tenderdash/internal/mempool:
    interfaces:
      Mempool:
  github.com/dashpay/tenderdash/internal/p2p:
    interfaces:
      Transport:
      Connection:
      Channel:
  github.com/dashpay/tenderdash/internal/p2p/client:
    interfaces:
      Client:
      BlockClient:
      SnapshotClient:
  github.com/dashpay/tenderdash/internal/state:
    interfaces:
      BlockStore:
      EvidencePool:
      Executor:
  github.com/dashpay/tenderdash/internal/state/indexer:
    interfaces:
      EventSink:
  github.com/dashpay/tenderdash/internal/statesync:
    interfaces:
      StateProvider:
  github.com/dashpay/tenderdash/libs/store:
    interfaces:
      Store:
  github.com/dashpay/tenderdash/light/provider:
    interfaces:
      Provider:
  github.com/dashpay/tenderdash/light/rpc:
    interfaces:
      LightClient:
  github.com/dashpay/tenderdash/rpc/client:
    interfaces:
      Client:
      RemoteClient:
  github.com/dashpay/tenderdash/types:
    interfaces:
      Store:
      PrivValidator:
      BlockEventPublisher:
