all: false
dir: "{{.InterfaceDir}}/mocks"
log-level: warn
structname: "{{.InterfaceName}}"
pkgname: mocks
template: testify
packages:
  github.com/dashpay/tenderdash/abci/client:
    interfaces:
      Client: {}
  github.com/dashpay/tenderdash/abci/types:
    interfaces:
      Application: {}
  github.com/dashpay/tenderdash/dash/core:
    interfaces:
      Client: {}
  github.com/dashpay/tenderdash/internal/consensus:
    interfaces:
      Gossiper: {}
  github.com/dashpay/tenderdash/internal/consensus/versioned/selectproposer:
    interfaces:
      ProposerSelector: {}
  github.com/dashpay/tenderdash/internal/evidence:
    interfaces:
      BlockStore: {}
  github.com/dashpay/tenderdash/internal/mempool:
    interfaces:
      Mempool: {}
  github.com/dashpay/tenderdash/internal/p2p:
    interfaces:
      Channel: {}
      Connection: {}
      Transport: {}
  github.com/dashpay/tenderdash/internal/p2p/client:
    interfaces:
      BlockClient: {}
      Client: {}
      SnapshotClient: {}
  github.com/dashpay/tenderdash/internal/state:
    interfaces:
      BlockStore: {}
      EvidencePool: {}
      Executor: {}
      Store: {}
  github.com/dashpay/tenderdash/internal/state/indexer:
    interfaces:
      EventSink: {}
  github.com/dashpay/tenderdash/internal/statesync:
    interfaces:
      StateProvider: {}
      ConsensusStateProvider: {}
  github.com/dashpay/tenderdash/libs/store:
    interfaces:
      Store: {}
  github.com/dashpay/tenderdash/light/provider:
    interfaces:
      Provider: {}
  github.com/dashpay/tenderdash/light/rpc:
    interfaces:
      LightClient: {}
  github.com/dashpay/tenderdash/rpc/client:
    interfaces:
      Client: {}
      RemoteClient: {}
  github.com/dashpay/tenderdash/types:
    interfaces:
      BlockEventPublisher: {}
      PrivValidator: {}
      Store: {}
