// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dashpay/tenderdash/internal/state"
	"github.com/dashpay/tenderdash/types"
	mock "github.com/stretchr/testify/mock"
)

// NewExecutor creates a new instance of Executor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Executor {
	mock := &Executor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Executor is an autogenerated mock type for the Executor type
type Executor struct {
	mock.Mock
}

type Executor_Expecter struct {
	mock *mock.Mock
}

func (_m *Executor) EXPECT() *Executor_Expecter {
	return &Executor_Expecter{mock: &_m.Mock}
}

// ApplyBlock provides a mock function for the type Executor
func (_mock *Executor) ApplyBlock(ctx context.Context, state1 state.State, blockID types.BlockID, block *types.Block, commit *types.Commit) (state.State, error) {
	ret := _mock.Called(ctx, state1, blockID, block, commit)

	if len(ret) == 0 {
		panic("no return value specified for ApplyBlock")
	}

	var r0 state.State
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.State, types.BlockID, *types.Block, *types.Commit) (state.State, error)); ok {
		return returnFunc(ctx, state1, blockID, block, commit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.State, types.BlockID, *types.Block, *types.Commit) state.State); ok {
		r0 = returnFunc(ctx, state1, blockID, block, commit)
	} else {
		r0 = ret.Get(0).(state.State)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.State, types.BlockID, *types.Block, *types.Commit) error); ok {
		r1 = returnFunc(ctx, state1, blockID, block, commit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Executor_ApplyBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyBlock'
type Executor_ApplyBlock_Call struct {
	*mock.Call
}

// ApplyBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - state1 state.State
//   - blockID types.BlockID
//   - block *types.Block
//   - commit *types.Commit
func (_e *Executor_Expecter) ApplyBlock(ctx interface{}, state1 interface{}, blockID interface{}, block interface{}, commit interface{}) *Executor_ApplyBlock_Call {
	return &Executor_ApplyBlock_Call{Call: _e.mock.On("ApplyBlock", ctx, state1, blockID, block, commit)}
}

func (_c *Executor_ApplyBlock_Call) Run(run func(ctx context.Context, state1 state.State, blockID types.BlockID, block *types.Block, commit *types.Commit)) *Executor_ApplyBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.State
		if args[1] != nil {
			arg1 = args[1].(state.State)
		}
		var arg2 types.BlockID
		if args[2] != nil {
			arg2 = args[2].(types.BlockID)
		}
		var arg3 *types.Block
		if args[3] != nil {
			arg3 = args[3].(*types.Block)
		}
		var arg4 *types.Commit
		if args[4] != nil {
			arg4 = args[4].(*types.Commit)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Executor_ApplyBlock_Call) Return(state11 state.State, err error) *Executor_ApplyBlock_Call {
	_c.Call.Return(state11, err)
	return _c
}

func (_c *Executor_ApplyBlock_Call) RunAndReturn(run func(ctx context.Context, state1 state.State, blockID types.BlockID, block *types.Block, commit *types.Commit) (state.State, error)) *Executor_ApplyBlock_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProposalBlock provides a mock function for the type Executor
func (_mock *Executor) CreateProposalBlock(ctx context.Context, height int64, round int32, state1 state.State, commit *types.Commit, proposerProTxHash []byte, proposedAppVersion uint64) (*types.Block, state.CurrentRoundState, error) {
	ret := _mock.Called(ctx, height, round, state1, commit, proposerProTxHash, proposedAppVersion)

	if len(ret) == 0 {
		panic("no return value specified for CreateProposalBlock")
	}

	var r0 *types.Block
	var r1 state.CurrentRoundState
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int32, state.State, *types.Commit, []byte, uint64) (*types.Block, state.CurrentRoundState, error)); ok {
		return returnFunc(ctx, height, round, state1, commit, proposerProTxHash, proposedAppVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int32, state.State, *types.Commit, []byte, uint64) *types.Block); ok {
		r0 = returnFunc(ctx, height, round, state1, commit, proposerProTxHash, proposedAppVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int32, state.State, *types.Commit, []byte, uint64) state.CurrentRoundState); ok {
		r1 = returnFunc(ctx, height, round, state1, commit, proposerProTxHash, proposedAppVersion)
	} else {
		r1 = ret.Get(1).(state.CurrentRoundState)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, int32, state.State, *types.Commit, []byte, uint64) error); ok {
		r2 = returnFunc(ctx, height, round, state1, commit, proposerProTxHash, proposedAppVersion)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Executor_CreateProposalBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProposalBlock'
type Executor_CreateProposalBlock_Call struct {
	*mock.Call
}

// CreateProposalBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - height int64
//   - round int32
//   - state1 state.State
//   - commit *types.Commit
//   - proposerProTxHash []byte
//   - proposedAppVersion uint64
func (_e *Executor_Expecter) CreateProposalBlock(ctx interface{}, height interface{}, round interface{}, state1 interface{}, commit interface{}, proposerProTxHash interface{}, proposedAppVersion interface{}) *Executor_CreateProposalBlock_Call {
	return &Executor_CreateProposalBlock_Call{Call: _e.mock.On("CreateProposalBlock", ctx, height, round, state1, commit, proposerProTxHash, proposedAppVersion)}
}

func (_c *Executor_CreateProposalBlock_Call) Run(run func(ctx context.Context, height int64, round int32, state1 state.State, commit *types.Commit, proposerProTxHash []byte, proposedAppVersion uint64)) *Executor_CreateProposalBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 state.State
		if args[3] != nil {
			arg3 = args[3].(state.State)
		}
		var arg4 *types.Commit
		if args[4] != nil {
			arg4 = args[4].(*types.Commit)
		}
		var arg5 []byte
		if args[5] != nil {
			arg5 = args[5].([]byte)
		}
		var arg6 uint64
		if args[6] != nil {
			arg6 = args[6].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *Executor_CreateProposalBlock_Call) Return(block *types.Block, currentRoundState state.CurrentRoundState, err error) *Executor_CreateProposalBlock_Call {
	_c.Call.Return(block, currentRoundState, err)
	return _c
}

func (_c *Executor_CreateProposalBlock_Call) RunAndReturn(run func(ctx context.Context, height int64, round int32, state1 state.State, commit *types.Commit, proposerProTxHash []byte, proposedAppVersion uint64) (*types.Block, state.CurrentRoundState, error)) *Executor_CreateProposalBlock_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendVote provides a mock function for the type Executor
func (_mock *Executor) ExtendVote(ctx context.Context, vote *types.Vote) {
	_mock.Called(ctx, vote)
	return
}

// Executor_ExtendVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendVote'
type Executor_ExtendVote_Call struct {
	*mock.Call
}

// ExtendVote is a helper method to define mock.On call
//   - ctx context.Context
//   - vote *types.Vote
func (_e *Executor_Expecter) ExtendVote(ctx interface{}, vote interface{}) *Executor_ExtendVote_Call {
	return &Executor_ExtendVote_Call{Call: _e.mock.On("ExtendVote", ctx, vote)}
}

func (_c *Executor_ExtendVote_Call) Run(run func(ctx context.Context, vote *types.Vote)) *Executor_ExtendVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Vote
		if args[1] != nil {
			arg1 = args[1].(*types.Vote)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Executor_ExtendVote_Call) Return() *Executor_ExtendVote_Call {
	_c.Call.Return()
	return _c
}

func (_c *Executor_ExtendVote_Call) RunAndReturn(run func(ctx context.Context, vote *types.Vote)) *Executor_ExtendVote_Call {
	_c.Run(run)
	return _c
}

// FinalizeBlock provides a mock function for the type Executor
func (_mock *Executor) FinalizeBlock(ctx context.Context, state1 state.State, uncommittedState state.CurrentRoundState, blockID types.BlockID, block *types.Block, commit *types.Commit) (state.State, error) {
	ret := _mock.Called(ctx, state1, uncommittedState, blockID, block, commit)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeBlock")
	}

	var r0 state.State
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.State, state.CurrentRoundState, types.BlockID, *types.Block, *types.Commit) (state.State, error)); ok {
		return returnFunc(ctx, state1, uncommittedState, blockID, block, commit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.State, state.CurrentRoundState, types.BlockID, *types.Block, *types.Commit) state.State); ok {
		r0 = returnFunc(ctx, state1, uncommittedState, blockID, block, commit)
	} else {
		r0 = ret.Get(0).(state.State)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.State, state.CurrentRoundState, types.BlockID, *types.Block, *types.Commit) error); ok {
		r1 = returnFunc(ctx, state1, uncommittedState, blockID, block, commit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Executor_FinalizeBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeBlock'
type Executor_FinalizeBlock_Call struct {
	*mock.Call
}

// FinalizeBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - state1 state.State
//   - uncommittedState state.CurrentRoundState
//   - blockID types.BlockID
//   - block *types.Block
//   - commit *types.Commit
func (_e *Executor_Expecter) FinalizeBlock(ctx interface{}, state1 interface{}, uncommittedState interface{}, blockID interface{}, block interface{}, commit interface{}) *Executor_FinalizeBlock_Call {
	return &Executor_FinalizeBlock_Call{Call: _e.mock.On("FinalizeBlock", ctx, state1, uncommittedState, blockID, block, commit)}
}

func (_c *Executor_FinalizeBlock_Call) Run(run func(ctx context.Context, state1 state.State, uncommittedState state.CurrentRoundState, blockID types.BlockID, block *types.Block, commit *types.Commit)) *Executor_FinalizeBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.State
		if args[1] != nil {
			arg1 = args[1].(state.State)
		}
		var arg2 state.CurrentRoundState
		if args[2] != nil {
			arg2 = args[2].(state.CurrentRoundState)
		}
		var arg3 types.BlockID
		if args[3] != nil {
			arg3 = args[3].(types.BlockID)
		}
		var arg4 *types.Block
		if args[4] != nil {
			arg4 = args[4].(*types.Block)
		}
		var arg5 *types.Commit
		if args[5] != nil {
			arg5 = args[5].(*types.Commit)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Executor_FinalizeBlock_Call) Return(state11 state.State, err error) *Executor_FinalizeBlock_Call {
	_c.Call.Return(state11, err)
	return _c
}

func (_c *Executor_FinalizeBlock_Call) RunAndReturn(run func(ctx context.Context, state1 state.State, uncommittedState state.CurrentRoundState, blockID types.BlockID, block *types.Block, commit *types.Commit) (state.State, error)) *Executor_FinalizeBlock_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessProposal provides a mock function for the type Executor
func (_mock *Executor) ProcessProposal(ctx context.Context, block *types.Block, round int32, state1 state.State, verify bool) (state.CurrentRoundState, error) {
	ret := _mock.Called(ctx, block, round, state1, verify)

	if len(ret) == 0 {
		panic("no return value specified for ProcessProposal")
	}

	var r0 state.CurrentRoundState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Block, int32, state.State, bool) (state.CurrentRoundState, error)); ok {
		return returnFunc(ctx, block, round, state1, verify)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Block, int32, state.State, bool) state.CurrentRoundState); ok {
		r0 = returnFunc(ctx, block, round, state1, verify)
	} else {
		r0 = ret.Get(0).(state.CurrentRoundState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Block, int32, state.State, bool) error); ok {
		r1 = returnFunc(ctx, block, round, state1, verify)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Executor_ProcessProposal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessProposal'
type Executor_ProcessProposal_Call struct {
	*mock.Call
}

// ProcessProposal is a helper method to define mock.On call
//   - ctx context.Context
//   - block *types.Block
//   - round int32
//   - state1 state.State
//   - verify bool
func (_e *Executor_Expecter) ProcessProposal(ctx interface{}, block interface{}, round interface{}, state1 interface{}, verify interface{}) *Executor_ProcessProposal_Call {
	return &Executor_ProcessProposal_Call{Call: _e.mock.On("ProcessProposal", ctx, block, round, state1, verify)}
}

func (_c *Executor_ProcessProposal_Call) Run(run func(ctx context.Context, block *types.Block, round int32, state1 state.State, verify bool)) *Executor_ProcessProposal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Block
		if args[1] != nil {
			arg1 = args[1].(*types.Block)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 state.State
		if args[3] != nil {
			arg3 = args[3].(state.State)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Executor_ProcessProposal_Call) Return(currentRoundState state.CurrentRoundState, err error) *Executor_ProcessProposal_Call {
	_c.Call.Return(currentRoundState, err)
	return _c
}

func (_c *Executor_ProcessProposal_Call) RunAndReturn(run func(ctx context.Context, block *types.Block, round int32, state1 state.State, verify bool) (state.CurrentRoundState, error)) *Executor_ProcessProposal_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateBlock provides a mock function for the type Executor
func (_mock *Executor) ValidateBlock(ctx context.Context, state1 state.State, block *types.Block) error {
	ret := _mock.Called(ctx, state1, block)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.State, *types.Block) error); ok {
		r0 = returnFunc(ctx, state1, block)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Executor_ValidateBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateBlock'
type Executor_ValidateBlock_Call struct {
	*mock.Call
}

// ValidateBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - state1 state.State
//   - block *types.Block
func (_e *Executor_Expecter) ValidateBlock(ctx interface{}, state1 interface{}, block interface{}) *Executor_ValidateBlock_Call {
	return &Executor_ValidateBlock_Call{Call: _e.mock.On("ValidateBlock", ctx, state1, block)}
}

func (_c *Executor_ValidateBlock_Call) Run(run func(ctx context.Context, state1 state.State, block *types.Block)) *Executor_ValidateBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.State
		if args[1] != nil {
			arg1 = args[1].(state.State)
		}
		var arg2 *types.Block
		if args[2] != nil {
			arg2 = args[2].(*types.Block)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Executor_ValidateBlock_Call) Return(err error) *Executor_ValidateBlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Executor_ValidateBlock_Call) RunAndReturn(run func(ctx context.Context, state1 state.State, block *types.Block) error) *Executor_ValidateBlock_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateBlockWithRoundState provides a mock function for the type Executor
func (_mock *Executor) ValidateBlockWithRoundState(ctx context.Context, state1 state.State, uncommittedState state.CurrentRoundState, block *types.Block) error {
	ret := _mock.Called(ctx, state1, uncommittedState, block)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBlockWithRoundState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.State, state.CurrentRoundState, *types.Block) error); ok {
		r0 = returnFunc(ctx, state1, uncommittedState, block)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Executor_ValidateBlockWithRoundState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateBlockWithRoundState'
type Executor_ValidateBlockWithRoundState_Call struct {
	*mock.Call
}

// ValidateBlockWithRoundState is a helper method to define mock.On call
//   - ctx context.Context
//   - state1 state.State
//   - uncommittedState state.CurrentRoundState
//   - block *types.Block
func (_e *Executor_Expecter) ValidateBlockWithRoundState(ctx interface{}, state1 interface{}, uncommittedState interface{}, block interface{}) *Executor_ValidateBlockWithRoundState_Call {
	return &Executor_ValidateBlockWithRoundState_Call{Call: _e.mock.On("ValidateBlockWithRoundState", ctx, state1, uncommittedState, block)}
}

func (_c *Executor_ValidateBlockWithRoundState_Call) Run(run func(ctx context.Context, state1 state.State, uncommittedState state.CurrentRoundState, block *types.Block)) *Executor_ValidateBlockWithRoundState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.State
		if args[1] != nil {
			arg1 = args[1].(state.State)
		}
		var arg2 state.CurrentRoundState
		if args[2] != nil {
			arg2 = args[2].(state.CurrentRoundState)
		}
		var arg3 *types.Block
		if args[3] != nil {
			arg3 = args[3].(*types.Block)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Executor_ValidateBlockWithRoundState_Call) Return(err error) *Executor_ValidateBlockWithRoundState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Executor_ValidateBlockWithRoundState_Call) RunAndReturn(run func(ctx context.Context, state1 state.State, uncommittedState state.CurrentRoundState, block *types.Block) error) *Executor_ValidateBlockWithRoundState_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyVoteExtension provides a mock function for the type Executor
func (_mock *Executor) VerifyVoteExtension(ctx context.Context, vote *types.Vote) error {
	ret := _mock.Called(ctx, vote)

	if len(ret) == 0 {
		panic("no return value specified for VerifyVoteExtension")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Vote) error); ok {
		r0 = returnFunc(ctx, vote)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Executor_VerifyVoteExtension_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyVoteExtension'
type Executor_VerifyVoteExtension_Call struct {
	*mock.Call
}

// VerifyVoteExtension is a helper method to define mock.On call
//   - ctx context.Context
//   - vote *types.Vote
func (_e *Executor_Expecter) VerifyVoteExtension(ctx interface{}, vote interface{}) *Executor_VerifyVoteExtension_Call {
	return &Executor_VerifyVoteExtension_Call{Call: _e.mock.On("VerifyVoteExtension", ctx, vote)}
}

func (_c *Executor_VerifyVoteExtension_Call) Run(run func(ctx context.Context, vote *types.Vote)) *Executor_VerifyVoteExtension_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Vote
		if args[1] != nil {
			arg1 = args[1].(*types.Vote)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Executor_VerifyVoteExtension_Call) Return(err error) *Executor_VerifyVoteExtension_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Executor_VerifyVoteExtension_Call) RunAndReturn(run func(ctx context.Context, vote *types.Vote) error) *Executor_VerifyVoteExtension_Call {
	_c.Call.Return(run)
	return _c
}
