---
name: Build
# Tests runs different tests (test_abci_apps, test_abci_cli, test_apps)
# This workflow runs on every push to master or release branch and  every pull requests
# All jobs will pass without running if no *{.go, .mod, .sum} files have been modified
on:
  pull_request:
  push:
    branches:
      - master
      - release/**
      - v0.*-dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goarch:
        - "amd64"
        # - "arm"
        goos: ["linux"]
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v3.1.0
        with:
          go-version: "1.18"
      - uses: actions/checkout@v2.4.0
      - uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            **/**.go
            "!test/"
            go.mod
            go.sum
            Makefile
      - uses: ./.github/actions/bls
        name: Install BLS library
        if: "env.GIT_DIFF != ''"
        with:
          arch: ${{ matrix.goarch }}
      - name: install-gcc
        run: sudo apt-get update -qq && sudo apt-get install -qq --yes gcc-10-arm-linux-gnueabi g++-10-arm-linux-gnueabi
        if: "matrix.goarch == 'arm'"        
      - name: install
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build-binary
        if: "env.GIT_DIFF != ''"
        shell: bash

  test_abci_cli:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v3.1.0
        with:
          go-version: "1.18"
      - uses: actions/checkout@v2.4.0
      - uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Install BLS library
        uses: ./.github/actions/bls
        if: "env.GIT_DIFF != ''"
      - name: install
        run: make install_abci
        if: "env.GIT_DIFF != ''"
      - run: abci/tests/test_cli/test.sh
        shell: bash
        if: "env.GIT_DIFF != ''"

  test_apps:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v3.1.0
        with:
          go-version: "1.18"
      - uses: actions/checkout@v2.4.0
      - uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: ./.github/actions/bls
        name: Install BLS library
        if: "env.GIT_DIFF != ''"
      - name: install
        run: make install install_abci
        if: "env.GIT_DIFF != ''"
      - name: test_apps
        run: test/app/test.sh
        shell: bash
        if: "env.GIT_DIFF != ''"
