# Verify that generated code is up-to-date.
#
# Note that we run these checks regardless whether the input files have
# changed, because generated code can change in response to toolchain updates
# even if no files in the repository are modified.
name: Check generated code
on:
  pull_request:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+-dev

permissions:
  contents: read

jobs:
  check-mocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6.0.0
        with:
          go-version: "1.24.2"

      - uses: actions/checkout@v4

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.go
          FILES: |
            .github/workflows/check-generated.yml

      - name: "Check generated mocks"
        if: env.GIT_DIFF
        run: |
          set -euo pipefail


          readonly MOCKERY=3.2.4  # N.B. no leading "v"
          curl -sL "https://github.com/vektra/mockery/releases/download/v${MOCKERY}/mockery_${MOCKERY}_Linux_x86_64.tar.gz" | tar -C /usr/local/bin -xzf -
          make mockery 2>/dev/null

          if ! git diff --exit-code ; then
            echo ">> ERROR:"
            echo ">>"
            echo ">> Generated mocks require update (either Mockery or source files may have changed)."
            echo ">> Ensure your tools are up-to-date, re-run 'make mockery' and update this PR."
            echo ">>"
            exit 1
          fi

  check-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6.0.0
        with:
          go-version: "1.24.2"

      - uses: actions/checkout@v4

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.proto

      - name: "Check protobuf generated code"
        if: env.GIT_DIFF
        run: |
          set -euo pipefail

          # Install buf and gogo tools, so that differences that arise from
          # toolchain differences are also caught.
          readonly tools="$(mktemp -d)"
          export PATH="${PATH}:${tools}/bin"
          export GOBIN="${tools}/bin"

          go install github.com/bufbuild/buf/cmd/buf
          # Forked version of gogoproto plugin with fix https://github.com/cosmos/gogoproto/pull/150
          # go install github.com/cosmos/gogoproto/protoc-gen-gogofaster@latest
          git clone --depth 1 --branch fix/panic-marshalto-nil-m \
            https://github.com/lklimek/gogoproto /tmp/gogoproto
          pushd /tmp/gogoproto
          go install ./protoc-gen-gogofaster
          popd
          rm -rf /tmp/gogoproto
          # End of forked version installation

          make proto-gen

          if ! git diff --stat --exit-code ; then
            echo ">> ERROR:"
            echo ">>"
            echo ">> Protobuf generated code requires update (either tools or .proto files may have changed)."
            echo ">> Ensure your tools are up-to-date, re-run 'make proto-gen' and update this PR."
            echo ">>"
            exit 1
          fi
