name: Test Coverage
on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  bls-signatures:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get BLS library revision
        id: bls-revision
        run: |
          echo "::set-output name=hash::$(git --git-dir=third_party/bls-signatures/src/.git rev-parse HEAD)"
        shell: bash
      - uses: actions/cache@v2
        id: bls-cache
        with:
          path: ~/bls-cache
          key: ${{ runner.os }}-bls-${{ steps.bls-revision.outputs.hash }}
      - name: Build BLS library
        run: make install-bls
        if: steps.bls-cache.outputs.cache-hit != 'true'
      - name: Save BLS library
        run: |
          mkdir -p ~/bls-cache/include
          cp -vr /usr/local/include/chiabls ~/bls-cache/include
          cp -vr /usr/local/include/relic* ~/bls-cache/include
          cp -v /usr/local/lib/libchiabls.a ~/bls-cache/
        if: steps.bls-cache.outputs.cache-hit != 'true'
      - uses: actions/cache@v2.1.2
        with:
          path: ~/bls-cache
          key: ${{ runner.os }}-bls-${{ steps.bls-revision.outputs.hash }}
        if: steps.bls-cache.outputs.cache-hit != 'true'

  split-test-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create a file with all the pkgs
        run: go list ./... > pkgs.txt
      - name: Split pkgs into 4 files
        run: split -d -n l/4 pkgs.txt pkgs.txt.part.
      # cache multiple
      - uses: actions/upload-artifact@v2
        with:
          name: "${{ github.sha }}-00"
          path: ./pkgs.txt.part.00
      - uses: actions/upload-artifact@v2
        with:
          name: "${{ github.sha }}-01"
          path: ./pkgs.txt.part.01
      - uses: actions/upload-artifact@v2
        with:
          name: "${{ github.sha }}-02"
          path: ./pkgs.txt.part.02
      - uses: actions/upload-artifact@v2
        with:
          name: "${{ github.sha }}-03"
          path: ./pkgs.txt.part.03

  build-linux:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goarch: ["arm", "amd64"]
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.4"
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: install
        run: GOOS=linux GOARCH=${{ matrix.goarch }} make build
        if: "env.GIT_DIFF != ''"

  tests:
    runs-on: ubuntu-latest
    needs: [bls-signatures, split-test-files]
    strategy:
      fail-fast: false
      matrix:
        part: ["00", "01", "02", "03"]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.4"
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/cache@v2
        with:
          path: ~/bls-cache
          key: ${{ runner.os }}-bls-${{ steps.bls-revision.outputs.hash }}
      - name: Install BLS library
        run: |
          sudo cp -vr ~/bls-cache/include/* /usr/local/include/
          sudo cp -vr ~/bls-cache/libchiabls.a /usr/local/lib/
      - uses: actions/download-artifact@v2
        with:
          name: "${{ github.sha }}-${{ matrix.part }}"
        if: env.GIT_DIFF
      - name: test & coverage report creation
        run: |
          cat pkgs.txt.part.${{ matrix.part }} | xargs go test -mod=readonly -timeout 8m -race -coverprofile=${{ matrix.part }}profile.out -covermode=atomic
        if: env.GIT_DIFF
      - uses: actions/upload-artifact@v2
        with:
          name: "${{ github.sha }}-${{ matrix.part }}-coverage"
          path: ./${{ matrix.part }}profile.out
  upload-coverage-report:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get BLS library revision
        id: bls-revision
        run: |
          echo "::set-output name=hash::$(git --git-dir=third_party/bls-signatures/src/.git rev-parse HEAD)"
        shell: bash
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/download-artifact@v2
        with:
          name: "${{ github.sha }}-00-coverage"
        if: env.GIT_DIFF
      - uses: actions/download-artifact@v2
        with:
          name: "${{ github.sha }}-01-coverage"
        if: env.GIT_DIFF
      - uses: actions/download-artifact@v2
        with:
          name: "${{ github.sha }}-02-coverage"
        if: env.GIT_DIFF
      - uses: actions/download-artifact@v2
        with:
          name: "${{ github.sha }}-03-coverage"
        if: env.GIT_DIFF
      - run: |
          cat ./*profile.out | grep -v "mode: atomic" >> coverage.txt
        if: env.GIT_DIFF
      - uses: codecov/codecov-action@v2.0.2
        with:
          file: ./coverage.txt
        if: env.GIT_DIFF
