---
name: Golang Linter
# Lint runs golangci-lint over the entire Tendermint repository.
#
# This workflow is run on every pull request and push to master.
#
# The `golangci` job will pass without running if no *.{go, mod, sum}
# files have been modified.

on:
  pull_request:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+-dev

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CGO_LDFLAGS: "-L/usr/local/lib -ldashbls -lrelic_s -lmimalloc-secure -lgmp"
      CGO_CXXFLAGS: "-I/usr/local/include"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            .github/linters/*
          FILES: |
            go.mod
            go.sum
            .golangci.yml

      - uses: actions/setup-go@v5.2.0
        if: env.GIT_DIFF
        with:
          go-version: "^1.23.2"

      - name: Install dependencies
        if: env.GIT_DIFF
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - uses: ./.github/actions/bls
        if: env.GIT_DIFF
        name: Install BLS library

      - uses: golangci/golangci-lint-action@v6.1.1
        if: env.GIT_DIFF
        with:
          # Required: the version of golangci-lint is required and
          # must be specified without patch version: we always use the
          # latest patch version.
          version: v1.61
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
          only-new-issues: true
